#===============================================
# Description: Update synchronization checker
# Lisence: MIT
# By：Jejz
#===============================================

name: Merge-upstream
on:
  schedule:
    - cron: 8 6,18 * * *
  workflow_dispatch:
  repository_dispatch:

jobs:
  merge:
    #if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set git identity
      run : |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"
        
    - name: Syn upstream
      run: |
        rm -rf ./*
        git clone https://github.com/xiaorouji/openwrt-passwall-packages ./
        rm -rf ./hysteria
        git clone https://github.com/fw876/helloworld ./
        rm -rf ./luci-app-ssr-plus

    - name: Apply
      run: |
        Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🛸" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git reset --soft HEAD^
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f
        
    - name: Delete workflow runs
      uses: Jejz168/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 3
